### ISSUE TITLE
Please support 2020-06-09 "Hogfather"

### ISSUE THREAD

**Issue by laoyur** [Medieninformatik-Regensburg/dokuwiki-plugin-markdowku#2]
Hi, I don't expect any new feature...
But could you please fix 2020-06-09 "Hogfather" support, it just crashes under Hogfather

**Comment by F10CH** [comment]
> Hi, I don't expect any new feature...
> But could you please fix 2020-06-09 "Hogfather" support, it just crashes under Hogfather

I confirm. All page are blank when using the plug-in.

You can temporarily deactivate it by writting `$plugins['markdowku'] = 0;` in `conf/plugins.local.php`

**Comment by Brazier85** [comment]
Just read the description on the dokuwiki plugin page. There you will find a link to a working version for the latsest version:

For Hogfather RC2, please use [https://github.com/Medieninformatik-Regensburg/dokuwiki-plugin-markdowku/archive/rc2.zip](this version) of the plugin (last updated 2020-06-06). (The link should be updated once Hogfather is officially released).

**Comment by Pallieter** [comment]
Deleting the 3 files will also work as a temporary solution:

lib/plugins/markdowku/syntax/blockquotes.php
lib/plugins/markdowku/syntax/olists.php
lib/plugins/markdowku/syntax/ulists.php

The error is with p_get_instructions

**Comment by issmirnov** [comment]
Hey @RaphaelWimmer , Hogfather is live and seems stable. Is it time to update the master branch?

**Comment by RaphaelWimmer** [comment]
> Hey @RaphaelWimmer , Hogfather is live and seems stable. Is it time to update the master branch?

Good point. I'm on vacation right now but will have a look in two weeks.

**Comment by fyr77** [comment]
Any updates on this?

**Comment by jasonfharris** [comment]
@RaphaelWimmer  Hey Raphael, can you switch over the support for hogfather to the newer version?

**Comment by natrius** [comment]
Any way this could be working soon? I can't upgrade until this works, i'm afraid nothing will work after updating without this plugin available :/

**Comment by louwers** [comment]
HogFather has been officially released a while back: https://www.dokuwiki.org/changes

**Comment by ThomasEnssner** [comment]
Hogfather is working, if you pull in the master-branch of this repo.

* remove your `/lib/plugins/markdowku` dir
* update your dokuwiki to the current hogfather version
* download [master](https://github.com/Medieninformatik-Regensburg/dokuwiki-plugin-markdowku/archive/master.zip)
* extract it to your `/lib/plugins/markdowku` 

**you can not use the extension manager to update or reinstall this plugin at the moment**

**Comment by Pallieter** [comment]
I can confirm this works as expected. And it lists in the extension manager (without an update button, so it looks normal).

**Comment by natrius** [comment]
It seems like some other plugin created the same problem. I got it solved now and markdowku shows up in the extensions manager, and it worked but just after deactivating and reactivating the extension.

**Comment by tboothman** [comment]
Is there any way to update the version on https://www.dokuwiki.org/plugin:markdowku to be the code in this repo? I updated by copying this repo's master into the plugins folder and it seems to work fine

**Comment by thoni56** [comment]
Thank you for rescuing this plugin and keeping it alive. I think it is one of the most valuable plugins since you don't have to learn yet another markup/down (and I'm not really fond of dokuwiki's native one...).

And it would be of great value to update the plugin in in the dokuwiki extension repo. If I can help in any way, I'll be glad to.

**Comment by thoni56** [comment]
Actually, as far as I understand (from this page: https://www.dokuwiki.org/devel:adoption), it is only a matter of creating a GitHub release (probably with the name `Hogfather`), which is just a few clicks.

Then update the `downloadurl` and `compatible` fields on the plugin page (https://www.dokuwiki.org/plugin:markdowku?do=edit).

But you should probably also clear up the text about how to fix the incompatibility (now that it is compatible ;-)).

**Comment by issmirnov** [comment]
@RaphaelWimmer can you do the update needed so that we can install through the plugin manager?

**Comment by snaeil** [comment]
Any progress on this?

**Comment by snaeil** [comment]
> Hogfather is working, if you pull in the master-branch of this repo.
> 
>     * remove your `/lib/plugins/markdowku` dir (**this is important, otherwise you will get an error 500**)
> 
>     * update your dokuwiki to the current hogfather version
> 
>     * download [master](https://github.com/Medieninformatik-Regensburg/dokuwiki-plugin-markdowku/archive/master.zip)
> 
>     * extract it to your `/lib/plugins/markdowku`
> 
> 
> **you can not use the extension manager to update or reinstall this plugin at the moment**

This is working for me. The plugin manager told me to name the directory `markdowku` also which I was doing.
I am still hoping @RaphaelWimmer can include this so that it can be installed with the plugin manger.
Otherwise, can you again promote this for adoption?

**Comment by RaphaelWimmer** [comment]
Sorry, I totally forgot this repo :(
Someone even sent me an email some time ago but I didn't have time to have a look at the issue back then.

I have just updated the repo and all links. Upgrading/installing Markdowku from the extension manager should work again now.
