### ISSUE TITLE
Outdated metadata in distributed version

### ISSUE THREAD

**Issue by thoschworks** [Medieninformatik-Regensburg/dokuwiki-plugin-markdowku#5]
After installing the plugin outdated metadata are shown in the Extension Manager:

![6EA96E18-C6DF-468F-A239-BEA3B500E5E9](https://user-images.githubusercontent.com/1668938/88832635-64ef5d00-d1d1-11ea-87f5-c3f929fe2c8a.jpeg)

The developer name and the link to the doku are still the old ones. The file `plugin.info.txt` was edited after the last upload.

**Comment by RaphaelWimmer** [comment]
Should be fixed now for the current version.
