### ISSUE TITLE
HTTP 500 error after installation on Hogfather

### ISSUE THREAD

**Issue by trasba** [Medieninformatik-Regensburg/dokuwiki-plugin-markdowku#7]
Hi after installing the plugin I instantly receive HTTP 500 error for every page.
After deleting the plugin folder everything is back to normal.

I run hogfather on an ubuntu xenial server.

Any ideas? Can I support you with some debug info, how so?

trasba

**Comment by banality13** [comment]
I can confirm this, on a Debian Buster server.

**Comment by traviswaelbro** [comment]
It seems `markdowku` still isn't officially supported on Hogfather (as shown on [the plugin page](https://www.dokuwiki.org/plugin:markdowku)). However, a workaround is discussed on #2 and I can confirm it works on Hogfather after the changes suggested there.

**Comment by RaphaelWimmer** [comment]
> It seems `markdowku` still isn't officially supported on Hogfather (as shown on [the plugin page](https://www.dokuwiki.org/plugin:markdowku)).

Sorry, *markdowku* is supported now - I just updated all code and links. 
So, updating/installing via the extension manager should work now.
